"""Global candidate refinement loop.

Implements top-N plan generation, bounded coordinate descent, beam
refinement, and immutable candidate history tracking.  This module
operates on proxy metrics from sensitivity reports; actual model
evaluation is delegated to the benchmark harness.
"""

from __future__ import annotations

import math
import re
import time
from dataclasses import dataclass

import structlog

from axquant.errors import RefinementError, ValidationGateError
from axquant.identity import same_model_identity
from axquant.module_paths import fused_expert_module, packed_expert_runtime_modules
from axquant.planner import plan_quantization, storage_bpw, strategy_for_measurement
from axquant.profiles import objective_for, thresholds_for
from axquant.schema import (
    Allocation,
    ArtifactManifest,
    CampaignDatasetRole,
    CandidateEntry,
    CandidateMeasurement,
    CompleteCandidateHardware,
    CompleteCandidateMeasurement,
    PlanRequest,
    PrecisionShare,
    QualityComparisonReport,
    QuantizationPlan,
    QuantMethod,
    RefinementConfig,
    RefinementMeasurementSet,
    RefinementResult,
    SensitivityReport,
    ValidationReport,
)
from axquant.serde import stable_sha256

log = structlog.get_logger()

COMPLETE_OBJECTIVE_VERSION = "axquant-complete-objective-v2"
_SHA256 = re.compile(r"^[0-9a-f]{64}$")


@dataclass
class _CandidateState:
    """Internal mutable state for a refinement candidate."""

    candidate_id: str
    plan: QuantizationPlan
    parent_id: str | None
    predicted_loss: float
    measured_loss: float | None = None
    change_description: str = "initial candidate"
    reason: str = "generated by greedy planner"
    budget_impact: float = 0.0
    state: str = "pending"


def _compute_plan_loss(plan: QuantizationPlan) -> float:
    """Compute aggregate predicted loss from a plan's allocations."""
    weights = objective_for(plan.profile).normalized()
    total_loss = 0.0
    total_params = 0
    for allocation in plan.assignments:
        metrics = allocation.metrics.model_dump()
        loss = sum(float(metrics[k]) * w for k, w in weights.items())
        total_loss += loss * allocation.parameters
        total_params += allocation.parameters
    return total_loss / total_params if total_params > 0 else 0.0


def _allocation_distribution(
    assignments: list[Allocation],
    *,
    mtp_only: bool = False,
) -> dict[str, PrecisionShare]:
    # Zero-parameter allocations are excluded exactly like the planner /
    # manual `_distribution` helpers and the plan schema validator; keeping
    # them would fail `precision_distributions_match_assignments` on rebuild.
    selected = [
        assignment
        for assignment in assignments
        if assignment.parameters > 0 and (not mtp_only or assignment.role.is_mtp)
    ]
    total_parameters = sum(assignment.parameters for assignment in selected)
    if total_parameters == 0:
        return {}
    parameters_by_precision: dict[str, int] = {}
    for assignment in selected:
        label = "bf16" if assignment.bits == 16 else f"{assignment.bits}bit"
        parameters_by_precision[label] = (
            parameters_by_precision.get(label, 0) + assignment.parameters
        )
    return {
        label: PrecisionShare(
            parameters=parameters,
            fraction=parameters / total_parameters,
        )
        for label, parameters in sorted(parameters_by_precision.items())
    }


def _rebuild_plan(
    plan: QuantizationPlan,
    assignments: list[Allocation],
) -> QuantizationPlan:
    """Recompute every assignment-derived plan summary and validate the result."""
    total_parameters = sum(assignment.parameters for assignment in assignments)
    if total_parameters <= 0:
        raise RefinementError("refined plan contains no logical parameters")
    nominal_bpw = (
        sum(assignment.bits * assignment.parameters for assignment in assignments)
        / total_parameters
    )
    effective_bpw = (
        sum(
            storage_bpw(assignment.bits, assignment.group_size) * assignment.parameters
            for assignment in assignments
        )
        / total_parameters
    )
    payload = plan.model_dump(mode="python")
    payload.update(
        {
            "assignments": assignments,
            "nominal_bpw": nominal_bpw,
            "effective_bpw": effective_bpw,
            "weight_distribution": _allocation_distribution(assignments),
            "mtp_distribution": _allocation_distribution(assignments, mtp_only=True),
        }
    )
    try:
        return QuantizationPlan.model_validate(payload)
    except ValueError as exc:
        raise RefinementError(f"refined plan is invalid: {exc}") from exc


def _require_plan_report_binding(
    plan: QuantizationPlan,
    report: SensitivityReport,
) -> None:
    if stable_sha256(report) != plan.analysis_sha256:
        raise RefinementError("refinement sensitivity report does not bind the candidate plan")
    if (
        not same_model_identity(report.model, plan.source_model)
        or report.profile != plan.profile
        or report.evidence_kind != plan.evidence_kind
        or report.calibration != plan.calibration
    ):
        raise RefinementError("refinement sensitivity identity differs from the candidate plan")
    # The planner intentionally stamps the registry's current support tier. All
    # immutable architecture facts must still match the producing report.
    normalized_plan_profile = plan.architecture_profile.model_copy(
        update={"support_tier": report.architecture_profile.support_tier}
    )
    if normalized_plan_profile != report.architecture_profile:
        raise RefinementError("refinement architecture profile differs from sensitivity evidence")


def _generate_candidate_id(seed: int, index: int) -> str:
    """Generate a deterministic candidate ID."""
    return f"cand-{seed:04d}-{index:03d}"


def _ax_engine_attention_packing_compatible(plan: QuantizationPlan) -> bool:
    """Require one quantization format for each Qwen attention Q/K/V pack.

    AX Engine packs ``q_proj``, ``k_proj``, and ``v_proj`` together.  MLX-LM
    can convert a mixed-format triplet, but the generated native manifest is
    invalid because the packed tensor layout is no longer representable.
    Reject those refinement variants before conversion rather than discovering
    the incompatibility after writing a full candidate checkpoint.
    """

    groups: dict[str, dict[str, tuple[int, QuantMethod, int | None]]] = {}
    for assignment in plan.assignments:
        marker = ".self_attn."
        if marker not in assignment.module_path:
            continue
        prefix, projection = assignment.module_path.rsplit(marker, 1)
        if projection not in {"q_proj", "k_proj", "v_proj"}:
            continue
        groups.setdefault(prefix, {})[projection] = (
            assignment.bits,
            assignment.method,
            assignment.group_size,
        )
    return all(
        len(set(group.values())) == 1
        for group in groups.values()
        if {"q_proj", "k_proj", "v_proj"}.issubset(group)
    )


def _is_packed_attention_projection(module_path: str) -> bool:
    marker = ".self_attn."
    return marker in module_path and module_path.rsplit(marker, 1)[1] in {
        "q_proj",
        "k_proj",
        "v_proj",
    }


def _is_monotonic_precision_refinement(
    parent: QuantizationPlan,
    child: QuantizationPlan,
) -> bool:
    """Return whether ``child`` only upgrades formats from ``parent``.

    M6 parentage represents an interaction refinement, not merely two plans generated at
    different budgets. A valid child must retain identical tensor coverage, never reduce a
    tensor's precision, and make at least one actual format change.
    """
    identity_fields = (
        "source_model",
        "architecture_profile",
        "profile",
        "candidate_bits",
        "group_size",
        "candidate_group_sizes",
        "objective",
        "hardware",
        "mtp",
        "primary_runtime",
        "analysis_sha256",
        "evidence_kind",
        "calibration",
    )
    if any(getattr(parent, field) != getattr(child, field) for field in identity_fields):
        return False
    parent_assignments = {assignment.tensor: assignment for assignment in parent.assignments}
    child_assignments = {assignment.tensor: assignment for assignment in child.assignments}
    if set(parent_assignments) != set(child_assignments):
        return False
    changed = False
    for tensor, parent_assignment in parent_assignments.items():
        child_assignment = child_assignments[tensor]
        if (
            child_assignment.module_path != parent_assignment.module_path
            or child_assignment.role != parent_assignment.role
            or child_assignment.parameters != parent_assignment.parameters
        ):
            return False
        if child_assignment.bits < parent_assignment.bits:
            return False
        if child_assignment.bits == parent_assignment.bits and (
            child_assignment.method != parent_assignment.method
            or child_assignment.group_size != parent_assignment.group_size
        ):
            return False
        if (
            child_assignment.bits,
            child_assignment.method,
            child_assignment.group_size,
        ) != (
            parent_assignment.bits,
            parent_assignment.method,
            parent_assignment.group_size,
        ):
            changed = True
    return changed and child.effective_bpw > parent.effective_bpw


def _canonicalize_ax_engine_attention_packs(
    plan: QuantizationPlan,
    report: SensitivityReport,
) -> QuantizationPlan:
    """Conservatively make each Qwen attention Q/K/V pack runtime-compatible.

    A per-tensor plan may assign different formats inside a packed Q/K/V
    group.  Canonicalize the group to its least-expensive existing format so
    the result remains within the planner budget.  Metrics are restored from
    the measured candidate for each affected tensor; this is not a synthetic
    sensitivity estimate.
    """

    _require_plan_report_binding(plan, report)
    entries = {entry.tensor.name: entry for entry in report.entries}
    if len(entries) != len(report.entries):
        raise RefinementError("sensitivity report contains duplicate tensor entries")
    groups: dict[str, list[tuple[int, Allocation]]] = {}
    for index, assignment in enumerate(plan.assignments):
        marker = ".self_attn."
        if marker not in assignment.module_path:
            continue
        prefix, projection = assignment.module_path.rsplit(marker, 1)
        if projection in {"q_proj", "k_proj", "v_proj"}:
            groups.setdefault(prefix, []).append((index, assignment))

    weights = objective_for(plan.profile).normalized()
    assignments = list(plan.assignments)
    changed = False
    for members in groups.values():
        projections = {
            assignment.module_path.rsplit(".self_attn.", 1)[1] for _, assignment in members
        }
        signatures = {
            (assignment.bits, assignment.method, assignment.group_size) for _, assignment in members
        }
        if projections != {"q_proj", "k_proj", "v_proj"} or len(signatures) == 1:
            continue
        candidate_maps = []
        for _index, assignment in members:
            entry = entries.get(assignment.tensor)
            if entry is None:
                raise RefinementError(f"missing sensitivity entry for {assignment.tensor}")
            candidate_maps.append(
                {
                    (item.bits, item.method, item.group_size): item
                    for item in entry.candidates
                    if item.supported
                }
            )
        common_signatures = set.intersection(
            *(set(candidate_map) for candidate_map in candidate_maps)
        )
        # Do not introduce a method/group that the original planner may have
        # excluded through a request-only method filter.
        legal_signatures = common_signatures & signatures
        if not legal_signatures:
            raise RefinementError(
                "packed attention tensors have no common measured format among "
                "their planned signatures"
            )
        current_storage = sum(
            storage_bpw(assignment.bits, assignment.group_size) * assignment.parameters
            for _index, assignment in members
        )

        def signature_key(
            signature: tuple[int, QuantMethod, int | None],
            member_records: list[tuple[int, Allocation]] = members,
            candidate_records: list[
                dict[tuple[int, QuantMethod, int | None], CandidateMeasurement]
            ] = candidate_maps,
        ) -> tuple[float, float, int, int, str]:
            aggregate_loss = 0.0
            for (_index, assignment), candidate_map in zip(
                member_records,
                candidate_records,
                strict=True,
            ):
                metrics = candidate_map[signature].metrics.model_dump()
                aggregate_loss += assignment.parameters * sum(
                    float(metrics[key]) * weight for key, weight in weights.items()
                )
            return (
                aggregate_loss,
                -storage_bpw(signature[0], signature[2]),
                signature[0],
                signature[2] or 0,
                signature[1].value,
            )

        budget_safe_signatures = {
            signature
            for signature in legal_signatures
            if storage_bpw(signature[0], signature[2])
            * sum(assignment.parameters for _index, assignment in members)
            <= current_storage + 1e-9
        }
        if not budget_safe_signatures:
            raise RefinementError(
                "packed attention tensors have no common format within their planned storage"
            )
        bits, method, group_size = min(budget_safe_signatures, key=signature_key)
        for index, assignment in members:
            entry = entries.get(assignment.tensor)
            if entry is None:
                raise RefinementError(f"missing sensitivity entry for {assignment.tensor}")
            candidate = next(
                (
                    item
                    for item in entry.candidates
                    if item.bits == bits
                    and item.method == method
                    and item.group_size == group_size
                    and item.supported
                ),
                None,
            )
            if candidate is None:
                raise RefinementError(
                    "no measured "
                    f"{bits}-bit candidate for packed attention tensor {assignment.tensor}"
                )
            metric_values = candidate.metrics.model_dump()
            scale_strategy, outlier_strategy = strategy_for_measurement(candidate)
            assignments[index] = assignment.model_copy(
                update={
                    "bits": bits,
                    "method": method,
                    "group_size": group_size,
                    "metrics": candidate.metrics,
                    "predicted_loss": sum(
                        float(metric_values[key]) * weight for key, weight in weights.items()
                    ),
                    "reason": "AX Engine packed Q/K/V format canonicalization",
                    "scale_strategy": scale_strategy,
                    "outlier_strategy": outlier_strategy,
                    "strategy_metadata": {
                        **assignment.strategy_metadata,
                        "storage_bpw": storage_bpw(bits, group_size),
                    },
                }
            )
            changed = True

    if not changed:
        return plan
    return _rebuild_plan(plan, assignments)


def generate_top_n_plans(
    report: SensitivityReport,
    request: PlanRequest,
    n: int,
    *,
    deadline: float | None = None,
) -> list[QuantizationPlan]:
    """Generate top-N plan variants via beam widening.

    The first plan is the standard greedy allocation.  Subsequent
    variants are produced by perturbing the least-efficient upgrades
    in the greedy solution.  Each variant remains deterministic under
    the plan seed.
    """
    if n < 1:
        raise RefinementError("top_n must be at least 1")

    # Generate the primary plan
    primary_request = request.model_copy(update={"candidate_count": 1})
    primary_plan = _canonicalize_ax_engine_attention_packs(
        plan_quantization(report, primary_request), report
    )
    if not _ax_engine_attention_packing_compatible(primary_plan):
        raise RefinementError("primary plan violates AX Engine attention packing")
    plans = [primary_plan]

    if n == 1:
        return plans

    # Generate an increasing precision ladder. Global replanning can occasionally exchange one
    # high-precision tensor for another even as the total budget grows. Such a plan remains a
    # useful independent candidate, but it is not an M6 parent/child refinement and is therefore
    # excluded from this monotonic interaction chain.
    base_bpw = request.target_bpw
    max_attempts = max(16, n * 4)
    for attempt in range(1, max_attempts + 1):
        if len(plans) >= n:
            break
        if deadline is not None and time.monotonic() >= deadline:
            log.info("refinement_generation_wall_clock_exhausted", plans=len(plans))
            break
        variant_bpw = min(16.0, base_bpw + attempt * 0.1)
        if variant_bpw <= plans[-1].target_bpw:
            break

        variant_request = request.model_copy(
            update={
                "candidate_count": 1,
                "target_bpw": variant_bpw,
                # Preserve the historical upward-variant seed identity. The original
                # alternating search assigned positive offsets to even attempt numbers.
                "random_seed": request.random_seed + attempt * 2,
            }
        )
        try:
            variant_plan = _canonicalize_ax_engine_attention_packs(
                plan_quantization(report, variant_request), report
            )
            if not _ax_engine_attention_packing_compatible(variant_plan):
                log.debug("variant_plan_incompatible", index=attempt, target_bpw=variant_bpw)
                continue
            if not _is_monotonic_precision_refinement(plans[-1], variant_plan):
                log.debug(
                    "variant_plan_non_monotonic",
                    index=attempt,
                    target_bpw=variant_bpw,
                )
                continue
            plans.append(variant_plan)
        except Exception:
            # If a variant is infeasible, skip it
            log.debug("variant_plan_infeasible", index=attempt, target_bpw=variant_bpw)
            continue

    return plans


def coordinate_descent_swap(
    plan: QuantizationPlan,
    report: SensitivityReport,
    request: PlanRequest,
    *,
    swap_radius: int = 5,
) -> QuantizationPlan | None:
    """Attempt bounded coordinate descent swaps on a plan.

    For each of the top-`swap_radius` tensors with highest predicted loss,
    try upgrading to the next precision level if budget allows.  Returns
    an improved plan or None if no improvement is found.
    """
    _require_plan_report_binding(plan, report)
    if request.profile != plan.profile:
        raise RefinementError("refinement request profile differs from the candidate plan")
    weights = objective_for(plan.profile).normalized()
    entries = {entry.tensor.name: entry for entry in report.entries}
    if len(entries) != len(report.entries):
        raise RefinementError("sensitivity report contains duplicate tensor entries")
    tied_targets = {
        entry.tensor.tied_to for entry in report.entries if entry.tensor.tied_to is not None
    }

    # Sort allocations by predicted loss (highest first)
    sorted_allocations = sorted(plan.assignments, key=lambda a: a.predicted_loss, reverse=True)
    candidates_to_try = sorted_allocations[:swap_radius]

    improved = False
    new_assignments = list(plan.assignments)

    for alloc in candidates_to_try:
        if alloc.bits >= 16 or _is_packed_attention_projection(alloc.module_path):
            continue

        # Find the sensitivity entry for this tensor
        entry = entries.get(alloc.tensor)
        if entry is None:
            raise RefinementError(f"missing sensitivity entry for {alloc.tensor}")
        if entry.tensor.tied_to is not None or alloc.tensor in tied_targets:
            # A one-coordinate mutation cannot preserve shared physical storage.
            continue
        if fused_expert_module(alloc.module_path) is not None:
            # A one-coordinate mutation cannot preserve fused-expert group
            # uniformity: every expert in a switch group must share one
            # (bits, method, group_size) signature or the conversion
            # predicate rejects the plan.
            continue

        # Try the closest precision upgrade that satisfies both the original
        # request grid and the hardware policy, and actually reduces measured
        # objective loss.
        legal_upgrades = []
        packed_expert = bool(packed_expert_runtime_modules(alloc.module_path))
        for candidate in entry.candidates:
            if (
                candidate.bits > alloc.bits
                and candidate.supported
                and candidate.bits in request.candidate_bits
                and candidate.bits in request.hardware.supported_bits
                and candidate.bits in plan.hardware.supported_bits
                and candidate.method in request.hardware.supported_methods
                and candidate.method in plan.hardware.supported_methods
                and (
                    not request.candidate_methods
                    or candidate.method in request.candidate_methods
                    or candidate.method == QuantMethod.BF16
                )
                and (
                    not packed_expert
                    or candidate.bits == 16
                    or candidate.method == QuantMethod.AFFINE
                )
                and (
                    candidate.bits == 16
                    or (
                        candidate.group_size in request.effective_group_sizes()
                        and candidate.group_size in request.hardware.supported_group_sizes
                        and candidate.group_size in plan.hardware.supported_group_sizes
                    )
                )
            ):
                metric_values = candidate.metrics.model_dump()
                candidate_loss = sum(
                    float(metric_values[key]) * weight for key, weight in weights.items()
                )
                if candidate_loss < alloc.predicted_loss - 1e-15:
                    legal_upgrades.append((candidate, candidate_loss))
        if not legal_upgrades:
            continue

        legal_upgrades.sort(
            key=lambda item: (
                item[0].bits,
                item[1],
                storage_bpw(item[0].bits, item[0].group_size),
                item[0].group_size or 0,
                item[0].method.value,
            )
        )
        upgrade = None
        upgraded_loss = 0.0
        for candidate, candidate_loss in legal_upgrades:
            current_storage = storage_bpw(alloc.bits, alloc.group_size) * alloc.parameters
            new_storage = storage_bpw(candidate.bits, candidate.group_size) * alloc.parameters
            budget_delta = (new_storage - current_storage) / sum(
                assignment.parameters for assignment in plan.assignments
            )
            if (
                plan.effective_bpw + budget_delta
                <= min(
                    request.target_bpw,
                    plan.target_bpw,
                )
                + 1e-9
            ):
                upgrade = candidate
                upgraded_loss = candidate_loss
                break
        if upgrade is None:
            continue

        # Apply the upgrade together with the candidate's metrics so that
        # downstream loss tracking reflects the new precision
        scale_strategy, outlier_strategy = strategy_for_measurement(upgrade)
        for i, a in enumerate(new_assignments):
            if a.tensor == alloc.tensor:
                new_assignments[i] = a.model_copy(
                    update={
                        "bits": upgrade.bits,
                        "method": upgrade.method,
                        "group_size": upgrade.group_size,
                        "metrics": upgrade.metrics,
                        "predicted_loss": upgraded_loss,
                        "reason": f"coordinate descent upgrade from {alloc.bits} to {upgrade.bits}",
                        "scale_strategy": scale_strategy,
                        "outlier_strategy": outlier_strategy,
                        "strategy_metadata": {
                            **a.strategy_metadata,
                            "storage_bpw": storage_bpw(upgrade.bits, upgrade.group_size),
                        },
                    }
                )
                improved = True
                break

        if improved:
            break  # One swap per iteration

    if not improved:
        return None

    refined = _rebuild_plan(plan, new_assignments)
    return refined if _ax_engine_attention_packing_compatible(refined) else None


def refine_candidates(
    report: SensitivityReport,
    request: PlanRequest,
    config: RefinementConfig,
) -> RefinementResult:
    """Run the global candidate refinement loop.

    1. Generate top-N initial plans
    2. Evaluate candidates (proxy-based in framework)
    3. Apply coordinate descent swaps
    4. Track immutable history
    5. Stop on convergence / budget exhaustion
    """
    start_time = time.monotonic()
    history: list[CandidateEntry] = []
    evaluations_used = 0

    # Step 1: Generate top-N initial plans
    plans = generate_top_n_plans(
        report,
        request,
        min(config.top_n, config.evaluation_budget),
        deadline=start_time + config.wall_clock_seconds,
    )
    if not plans:
        raise RefinementError("no feasible plans could be generated")

    # Track candidate states
    candidates: list[_CandidateState] = []
    for i, plan in enumerate(plans):
        cand_id = _generate_candidate_id(config.random_seed, i)
        parent_id = None if i == 0 else _generate_candidate_id(config.random_seed, i - 1)
        loss = _compute_plan_loss(plan)
        state = _CandidateState(
            candidate_id=cand_id,
            plan=plan,
            parent_id=parent_id,
            predicted_loss=loss,
            change_description=(
                "initial greedy plan"
                if i == 0
                else f"budget-perturbed precision allocation variant {i}"
            ),
            reason=(
                "top-N generation"
                if i == 0
                else f"monotonic top-N precision refinement of {parent_id}"
            ),
            budget_impact=plan.effective_bpw - request.target_bpw,
        )
        candidates.append(state)
        history.append(
            CandidateEntry(
                candidate_id=cand_id,
                parent_id=parent_id,
                plan_sha256=stable_sha256(plan),
                change_description=state.change_description,
                reason=state.reason,
                predicted_bpw=plan.effective_bpw,
                predicted_loss=loss,
                budget_impact=state.budget_impact,
                state="pending",
            )
        )
        evaluations_used += 1

    # Step 2-5: Iterative refinement
    converged = False
    iterations_used = 0

    for iteration in range(config.max_iterations):
        iterations_used = iteration + 1

        # Check wall-clock budget
        elapsed = time.monotonic() - start_time
        if elapsed > config.wall_clock_seconds:
            log.info("refinement_wall_clock_exhausted", elapsed=elapsed)
            break

        # Check evaluation budget
        if evaluations_used >= config.evaluation_budget:
            log.info("refinement_eval_budget_exhausted", evaluations=evaluations_used)
            break

        # Select the current best candidate
        best_candidate = min(candidates, key=lambda c: c.predicted_loss)

        # Try coordinate descent within the candidate's own search budget.  Top-N
        # variants intentionally widen or tighten the original request, and
        # reusing the primary budget makes every widened variant impossible to
        # refine further.
        candidate_request = request.model_copy(
            update={
                "target_bpw": best_candidate.plan.target_bpw,
                "random_seed": best_candidate.plan.random_seed,
            }
        )
        improved_plan = coordinate_descent_swap(
            best_candidate.plan,
            report,
            candidate_request,
            swap_radius=config.swap_radius,
        )

        if improved_plan is None:
            # No improvement found - check convergence
            converged = True
            break

        new_loss = _compute_plan_loss(improved_plan)
        improvement = best_candidate.predicted_loss - new_loss

        # Check convergence threshold
        if improvement <= config.convergence_threshold:
            converged = True
            break

        # Record the improved candidate
        new_id = _generate_candidate_id(config.random_seed, len(candidates) + iterations_used)
        new_state = _CandidateState(
            candidate_id=new_id,
            plan=improved_plan,
            parent_id=best_candidate.candidate_id,
            predicted_loss=new_loss,
            change_description=(
                f"coordinate descent swap: {best_candidate.predicted_loss:.6f} -> {new_loss:.6f}"
            ),
            reason=f"improvement of {improvement:.6f} via precision upgrade",
            budget_impact=improved_plan.effective_bpw - request.target_bpw,
            state="selected",
        )
        candidates.append(new_state)
        evaluations_used += 1

        history.append(
            CandidateEntry(
                candidate_id=new_id,
                parent_id=best_candidate.candidate_id,
                plan_sha256=stable_sha256(improved_plan),
                change_description=new_state.change_description,
                reason=new_state.reason,
                predicted_bpw=improved_plan.effective_bpw,
                predicted_loss=new_loss,
                budget_impact=new_state.budget_impact,
                state="selected",
            )
        )

        log.debug(
            "refinement_iteration",
            iteration=iterations_used,
            loss=new_loss,
            improvement=improvement,
        )

    # Select the final best candidate
    final_best = min(candidates, key=lambda c: c.predicted_loss)
    selected_sha = stable_sha256(final_best.plan)

    # A refinement history has exactly one selected state. Intermediate
    # candidates may have been provisionally selected while searching, but are
    # immutable evidence records rather than multiple final selections.
    for entry in history:
        entry.state = "selected" if entry.candidate_id == final_best.candidate_id else "rejected"

    proxy_warning = (
        "Proxy-only refinement is development evidence and cannot satisfy release "
        "selection without holdout-bound complete-candidate measurements (QP1)."
    )
    warnings = [proxy_warning]
    if config.holdout_measurement_set_sha256:
        warnings.append(
            "holdout_measurement_set_sha256 is configured; call select_complete_candidate "
            "with a matching RefinementMeasurementSet to bind holdout evidence."
        )
    return RefinementResult(
        config=config,
        history=history,
        candidate_plans={candidate.candidate_id: candidate.plan for candidate in candidates},
        selected_candidate_id=final_best.candidate_id,
        selected_plan=final_best.plan,
        selected_plan_sha256=selected_sha,
        selection_basis="proxy",
        evidence_label="proxy-development",
        holdout_measurement_set_sha256=config.holdout_measurement_set_sha256,
        warnings=warnings,
        iterations_used=iterations_used,
        evaluations_used=evaluations_used,
        converged=converged,
    )


def _complete_objective_loss(
    plan: QuantizationPlan,
    *,
    quality_retention: float,
    perplexity_ratio: float,
    mtp_acceptance_retention: float,
    mtp_speedup: float,
    peak_memory_ratio: float,
) -> float:
    values = {
        "quality_retention": quality_retention,
        "perplexity_ratio": perplexity_ratio,
        "mtp_acceptance_retention": mtp_acceptance_retention,
        "mtp_speedup": mtp_speedup,
        "peak_memory_ratio": peak_memory_ratio,
    }
    for name, value in values.items():
        if not math.isfinite(value):
            raise RefinementError(f"complete-candidate {name} must be finite")
    if perplexity_ratio <= 0.0:
        raise RefinementError("complete-candidate perplexity_ratio must be positive")
    if mtp_speedup <= 0.0:
        raise RefinementError("complete-candidate mtp_speedup must be positive")
    if peak_memory_ratio <= 0.0:
        raise RefinementError("complete-candidate peak_memory_ratio must be positive")

    weights = objective_for(plan.profile).normalized()
    quality_weight = (
        weights["output_kl"]
        + weights["hidden_state_error"]
        + weights["cosine_distance"]
        + weights["token_disagreement"]
        + weights["task_loss_delta"]
        + weights["long_context_loss"]
    )
    latency_weight = weights["prefill_latency_cost"] + weights["decode_latency_cost"]
    quality_loss = 0.5 * max(0.0, 1.0 - quality_retention) + 0.5 * perplexity_ratio
    return (
        quality_weight * quality_loss
        + weights["mtp_acceptance_loss"] * max(0.0, 1.0 - mtp_acceptance_retention)
        + weights["peak_memory_cost"] * peak_memory_ratio
        + latency_weight / mtp_speedup
    )


def _validate_complete_measurement(
    *,
    plan: QuantizationPlan,
    history_plan_sha256: str,
    measurement: CompleteCandidateMeasurement,
) -> None:
    plan_sha256 = stable_sha256(plan)
    if history_plan_sha256 != plan_sha256:
        raise RefinementError(
            f"refinement history plan digest differs for {measurement.candidate_id}"
        )
    if measurement.plan_sha256 != plan_sha256:
        raise RefinementError(f"measurement plan digest differs for {measurement.candidate_id}")
    if measurement.profile != plan.profile:
        raise RefinementError(f"measurement profile differs for {measurement.candidate_id}")
    for label, digest in (
        ("artifact manifest", measurement.artifact_manifest_sha256),
        ("quality comparison", measurement.quality_comparison_sha256),
        ("validation", measurement.validation_sha256),
    ):
        if _SHA256.fullmatch(digest) is None:
            raise RefinementError(
                f"measurement {label} digest is invalid for {measurement.candidate_id}"
            )
    if not measurement.validation_passed:
        return

    if measurement.perplexity_ratio is None:
        raise RefinementError(
            f"passing measurement has no perplexity ratio for {measurement.candidate_id}"
        )
    expected_loss = _complete_objective_loss(
        plan,
        quality_retention=measurement.quality_retention,
        perplexity_ratio=measurement.perplexity_ratio,
        mtp_acceptance_retention=measurement.mtp_acceptance_retention,
        mtp_speedup=measurement.mtp_speedup,
        peak_memory_ratio=measurement.peak_memory_ratio,
    )
    if not math.isclose(
        measurement.objective_loss,
        expected_loss,
        rel_tol=1e-12,
        abs_tol=1e-12,
    ):
        raise RefinementError(f"measurement objective differs for {measurement.candidate_id}")

    thresholds = thresholds_for(plan.profile)
    failed_metrics: list[str] = []
    if measurement.quality_retention < thresholds.minimum_aggregate_quality_retention:
        failed_metrics.append("quality_retention")
    if measurement.perplexity_ratio > 1.0 + thresholds.max_perplexity_relative_increase:
        failed_metrics.append("perplexity_ratio")
    if measurement.mtp_acceptance_retention < thresholds.minimum_mtp_acceptance_retention:
        failed_metrics.append("mtp_acceptance_retention")
    if measurement.mtp_speedup < thresholds.min_effective_speedup:
        failed_metrics.append("mtp_speedup")
    if measurement.peak_memory_ratio > thresholds.max_peak_memory_ratio:
        failed_metrics.append("peak_memory_ratio")
    if measurement.hardware.kernel_fallbacks != 0:
        failed_metrics.append("kernel_fallbacks")
    if failed_metrics:
        raise RefinementError(
            f"passing measurement fails release metrics for "
            f"{measurement.candidate_id}: {failed_metrics}"
        )


# ADR-0004: formal holdout roles are consumed-on-contact and must never feed
# the interaction-optimization loop. Values mirror CampaignDatasetRole.
FORMAL_HOLDOUT_ROLES = frozenset(
    {
        CampaignDatasetRole.FORMAL_AGENT_CODING.value,
        CampaignDatasetRole.FORMAL_GENERAL.value,
    }
)


def guard_interaction_measurement_roles(measurements: RefinementMeasurementSet) -> None:
    """Fail closed unless every measurement proves a non-holdout dataset role."""
    holdout = sorted(
        {
            measurement.measurement_id
            for measurement in measurements.measurements
            if measurement.dataset_role in FORMAL_HOLDOUT_ROLES
        }
    )
    if holdout:
        raise RefinementError(
            "interaction optimization must never consume formal holdout "
            f"measurements: {holdout[:10]}"
        )
    unproven = sorted(
        {
            measurement.measurement_id
            for measurement in measurements.measurements
            if not measurement.dataset_role.strip()
        }
    )
    if unproven:
        raise RefinementError(
            "interaction optimization requires dataset-role provenance on every "
            f"measurement; missing for: {unproven[:10]}"
        )


def optimize_candidate_interactions(
    refinement: RefinementResult,
    measurements: RefinementMeasurementSet,
) -> RefinementResult:
    """Measured interaction optimization on non-holdout roles (RM-11 / ADR-0004).

    Runs the same checksum-bound complete-model selection as
    ``select_complete_candidate`` but structurally cannot read formal holdout
    evidence: every measurement must carry a development/validation dataset
    role. The result is labeled ``interaction-development`` — it never claims
    holdout binding, and the formal holdout still sees the frozen winner
    exactly once.
    """
    guard_interaction_measurement_roles(measurements)
    return _select_from_measurements(
        refinement,
        measurements,
        mode="interaction",
        evidence_label="interaction-development",
        selection_note=(
            "Selection driven by interaction-development complete-candidate "
            "measurements (digest {digest}); formal holdout remains unconsumed."
        ),
    )


def select_complete_candidate(
    refinement: RefinementResult,
    measurements: RefinementMeasurementSet,
) -> RefinementResult:
    """Select a candidate only from checksum-bound complete-model evidence."""
    return _select_from_measurements(
        refinement,
        measurements,
        mode="holdout",
        evidence_label="holdout-bound",
        selection_note=(
            "Selection bound to holdout complete-candidate measurements (digest {digest})."
        ),
    )


def _select_from_measurements(
    refinement: RefinementResult,
    measurements: RefinementMeasurementSet,
    *,
    mode: str,
    evidence_label: str,
    selection_note: str,
) -> RefinementResult:
    measurement_digest = stable_sha256(measurements)
    if not measurements.evaluator_version.strip():
        raise RefinementError("measurement set evaluator version is empty")
    if mode == "interaction":
        # Interaction measurements always bind the refinement result directly;
        # any configured holdout digest describes a different, future set.
        if measurements.refinement_sha256 != stable_sha256(refinement):
            raise RefinementError("measurement set does not bind the refinement result")
    else:
        configured_holdout = refinement.config.holdout_measurement_set_sha256
        recorded_holdout = refinement.holdout_measurement_set_sha256
        if (
            configured_holdout is not None
            and recorded_holdout is not None
            and configured_holdout != recorded_holdout
        ):
            raise RefinementError("refinement contains conflicting holdout measurement bindings")
        expected_holdout = configured_holdout or recorded_holdout
        if expected_holdout is not None and measurement_digest != expected_holdout:
            raise RefinementError(
                "holdout measurement set digest does not match refinement binding: "
                f"expected {expected_holdout}, got {measurement_digest}"
            )
        # An explicit holdout digest and the measurement set's refinement digest
        # cannot both include one another without a circular hash. In the ordinary
        # unconfigured workflow, require the measurement set's direct binding.
        if expected_holdout is None and measurements.refinement_sha256 != stable_sha256(refinement):
            raise RefinementError("measurement set does not bind the refinement result")
    candidates_by_id = refinement.candidate_plans
    history_ids = [entry.candidate_id for entry in refinement.history]
    if len(history_ids) != len(set(history_ids)):
        raise RefinementError("refinement history contains duplicate candidate IDs")
    history_by_id = {entry.candidate_id: entry for entry in refinement.history}
    if set(history_by_id) != set(candidates_by_id):
        raise RefinementError("refinement history and candidate plans have different coverage")
    measurements_by_candidate: dict[str, list[CompleteCandidateMeasurement]] = {}
    for measurement_record in measurements.measurements:
        history = history_by_id.get(measurement_record.candidate_id)
        if measurement_record.candidate_id not in candidates_by_id or history is None:
            raise RefinementError(
                f"measurement references unknown candidate {measurement_record.candidate_id}"
            )
        plan = candidates_by_id[measurement_record.candidate_id]
        _validate_complete_measurement(
            plan=plan,
            history_plan_sha256=history.plan_sha256,
            measurement=measurement_record,
        )
        measurements_by_candidate.setdefault(measurement_record.candidate_id, []).append(
            measurement_record
        )
    for candidate_id, records in measurements_by_candidate.items():
        candidate_models = {stable_sha256(record.candidate_model) for record in records}
        if len(candidate_models) != 1:
            raise RefinementError(f"measurements identify different checkpoints for {candidate_id}")
    valid = {
        candidate_id: records
        for candidate_id, records in measurements_by_candidate.items()
        if all(record.validation_passed for record in records)
    }
    if not valid:
        raise RefinementError("no complete-model candidate passed validation")
    selected_candidate_id, _selected_measurements = min(
        valid.items(),
        key=lambda item: (
            max(record.objective_loss for record in item[1]),
            max(record.measured_bpw for record in item[1]),
            item[0],
        ),
    )
    updated_history = []
    for entry in refinement.history:
        complete_measurements = measurements_by_candidate.get(entry.candidate_id, [])
        updated_history.append(
            entry.model_copy(
                update={
                    "measured_bpw": (
                        max(record.measured_bpw for record in complete_measurements)
                        if complete_measurements
                        else None
                    ),
                    "measured_loss": (
                        max(record.objective_loss for record in complete_measurements)
                        if complete_measurements
                        else None
                    ),
                    "state": (
                        "selected" if entry.candidate_id == selected_candidate_id else "rejected"
                    ),
                }
            )
        )
    selected_plan = candidates_by_id[selected_candidate_id]
    warnings = [
        warning for warning in refinement.warnings if "Proxy-only refinement" not in warning
    ]
    warnings.append(selection_note.format(digest=measurement_digest))
    binding_field = (
        "interaction_measurement_set_sha256"
        if mode == "interaction"
        else "holdout_measurement_set_sha256"
    )
    return refinement.model_copy(
        update={
            "history": updated_history,
            "selected_candidate_id": selected_candidate_id,
            "selected_plan": selected_plan,
            "selected_plan_sha256": stable_sha256(selected_plan),
            "selection_basis": "complete-model",
            "evidence_label": evidence_label,
            binding_field: measurement_digest,
            "warnings": warnings,
        }
    )


def build_complete_candidate_measurement(
    *,
    candidate_id: str,
    measurement_id: str | None = None,
    plan: QuantizationPlan,
    artifact: ArtifactManifest,
    artifact_sha256: str,
    quality: QualityComparisonReport,
    quality_sha256: str,
    validation: ValidationReport,
    validation_sha256: str,
    dataset_role: str = "",
) -> CompleteCandidateMeasurement:
    """Build checksum-bound complete-model evidence from release artifacts."""
    for label, digest in (
        ("artifact manifest", artifact_sha256),
        ("quality comparison", quality_sha256),
        ("validation", validation_sha256),
    ):
        if _SHA256.fullmatch(digest) is None:
            raise RefinementError(f"{label} digest is not a valid SHA-256")
    plan_sha256 = stable_sha256(plan)
    if artifact.plan_sha256 != plan_sha256:
        raise RefinementError("artifact manifest does not match the refinement candidate plan")
    if (
        not same_model_identity(artifact.source_model, plan.source_model)
        or artifact.calibration != plan.calibration
        or artifact.target_class != plan.target_class
        or artifact.mtp_policy != plan.mtp
        or artifact.software_versions != plan.software_versions
        or artifact.weight_distribution != plan.weight_distribution
        or artifact.mtp_distribution != plan.mtp_distribution
        or artifact.logical_parameters
        != sum(assignment.parameters for assignment in plan.assignments)
        or not math.isclose(
            artifact.effective_bpw,
            plan.effective_bpw,
            rel_tol=0.0,
            abs_tol=1e-9,
        )
    ):
        raise RefinementError("artifact manifest metadata differs from the candidate plan")
    if artifact.profile != plan.profile or validation.profile != plan.profile:
        raise RefinementError("artifact, validation, and candidate plan profiles differ")
    if not same_model_identity(quality.candidate_model, validation.candidate_model):
        raise RefinementError("quality and validation candidate identities differ")
    if not same_model_identity(quality.reference_model, validation.reference_model):
        raise RefinementError("quality and validation reference identities differ")
    if validation.thresholds != thresholds_for(plan.profile):
        raise RefinementError("validation does not use the authoritative profile thresholds")
    expected_validation_passed = not any(issue.severity == "error" for issue in validation.issues)
    if validation.passed != expected_validation_passed:
        raise RefinementError("validation pass status is inconsistent with its issues")
    if validation.comparisons.get("artifact.candidate_source_sha256") != artifact_sha256:
        raise RefinementError("validation size evidence does not bind the artifact manifest")
    if (
        validation.comparisons.get("artifact.candidate_weight_bytes")
        != artifact.weight_file_size_bytes
    ):
        raise RefinementError("validation size evidence does not match artifact weight bytes")

    quality_retention = quality.aggregate.retention
    if quality_retention is None:
        raise RefinementError("quality comparison has no aggregate retention")
    perplexity_ratio = quality.perplexity_ratio
    if perplexity_ratio is None or perplexity_ratio <= 0.0:
        raise RefinementError("quality comparison has no positive perplexity ratio")

    def required_metric(name: str) -> float:
        value = validation.comparisons.get(name)
        if not isinstance(value, (int, float)) or isinstance(value, bool):
            raise RefinementError(f"validation is missing numeric {name}")
        numeric = float(value)
        if not math.isfinite(numeric):
            raise RefinementError(f"validation contains non-finite {name}")
        return numeric

    def required_text(name: str) -> str:
        value = validation.comparisons.get(name)
        if not isinstance(value, str) or not value.strip():
            raise RefinementError(f"validation is missing {name}")
        return value

    unified_memory = validation.comparisons.get("hardware.unified_memory_bytes")
    if (
        not isinstance(unified_memory, int)
        or isinstance(unified_memory, bool)
        or unified_memory <= 0
    ):
        raise RefinementError("validation is missing hardware.unified_memory_bytes")

    mtp_retention = required_metric("mtp.acceptance_retention")
    mtp_speedup = required_metric("hardware.effective_speedup")
    peak_memory_ratio = required_metric("hardware.peak_memory_ratio")
    kernel_fallbacks = validation.comparisons.get("hardware.kernel_fallbacks")
    if not isinstance(kernel_fallbacks, int) or isinstance(kernel_fallbacks, bool):
        raise RefinementError("validation is missing hardware.kernel_fallbacks")
    quality_validation_retention = required_metric("quality.aggregate_retention")
    perplexity_relative_increase = required_metric("perplexity_relative_increase")
    if not math.isclose(
        quality_validation_retention,
        quality_retention,
        rel_tol=1e-12,
        abs_tol=1e-12,
    ):
        raise RefinementError("quality comparison retention does not match validation evidence")
    if not math.isclose(
        1.0 + perplexity_relative_increase,
        perplexity_ratio,
        rel_tol=1e-12,
        abs_tol=1e-12,
    ):
        raise RefinementError("quality comparison perplexity does not match validation evidence")

    if validation.passed:
        thresholds = validation.thresholds
        failed_release_metrics: list[str] = []
        if quality_retention < thresholds.minimum_aggregate_quality_retention:
            failed_release_metrics.append("quality.aggregate_retention")
        if perplexity_ratio > 1.0 + thresholds.max_perplexity_relative_increase:
            failed_release_metrics.append("quality.perplexity_ratio")
        if mtp_retention < thresholds.minimum_mtp_acceptance_retention:
            failed_release_metrics.append("mtp.acceptance_retention")
        if mtp_speedup < thresholds.min_effective_speedup:
            failed_release_metrics.append("hardware.effective_speedup")
        if peak_memory_ratio > thresholds.max_peak_memory_ratio:
            failed_release_metrics.append("hardware.peak_memory_ratio")
        if kernel_fallbacks != 0:
            failed_release_metrics.append("hardware.kernel_fallbacks")
        if failed_release_metrics:
            raise RefinementError(
                "passing validation contains failed complete-model metrics: "
                f"{failed_release_metrics}"
            )

        if thresholds.require_artifact_size:
            size_ratio = required_metric("artifact.weight_size_ratio")
            if size_ratio > thresholds.max_weight_size_ratio:
                from axquant.release_exceptions import release_exception_allows_size

                try:
                    release_exception_allows_size(validation, plan=plan)
                except (ValidationGateError, ValueError) as exc:
                    raise RefinementError(
                        f"passing validation has an ungoverned size overage: {exc}"
                    ) from exc
            elif validation.release_exceptions:
                raise RefinementError(
                    "passing validation contains an unnecessary release exception"
                )
        elif validation.release_exceptions:
            raise RefinementError(
                "validation without an artifact-size gate contains a release exception"
            )

    objective_loss = _complete_objective_loss(
        plan,
        quality_retention=quality_retention,
        perplexity_ratio=perplexity_ratio,
        mtp_acceptance_retention=mtp_retention,
        mtp_speedup=mtp_speedup,
        peak_memory_ratio=peak_memory_ratio,
    )
    return CompleteCandidateMeasurement(
        candidate_id=candidate_id,
        measurement_id=measurement_id or candidate_id,
        candidate_model=validation.candidate_model,
        profile=plan.profile,
        dataset_role=dataset_role,
        plan_sha256=plan_sha256,
        artifact_manifest_sha256=artifact_sha256,
        quality_comparison_sha256=quality_sha256,
        validation_sha256=validation_sha256,
        measured_bpw=artifact.measured_total_bpw,
        objective_loss=objective_loss,
        quality_retention=quality_retention,
        perplexity_ratio=perplexity_ratio,
        mtp_acceptance_retention=mtp_retention,
        mtp_speedup=mtp_speedup,
        peak_memory_ratio=peak_memory_ratio,
        hardware=CompleteCandidateHardware(
            device_name=required_text("hardware.device_name"),
            chip=required_text("hardware.chip"),
            unified_memory_bytes=unified_memory,
            os_version=required_text("hardware.os_version"),
            ax_engine_version=required_text("software.ax_engine"),
            mlx_version=required_text("software.mlx"),
            mlx_lm_version=required_text("software.mlx_lm"),
            power_mode=required_text("hardware.power_mode"),
            kernel_fallbacks=kernel_fallbacks,
        ),
        validation_passed=validation.passed,
    )
