"""Global candidate refinement loop.

Implements top-N plan generation, bounded coordinate descent, beam
refinement, and immutable candidate history tracking.  This module
operates on proxy metrics from sensitivity reports; actual model
evaluation is delegated to the benchmark harness.
"""

from __future__ import annotations

import time
from dataclasses import dataclass

import structlog

from axquant.errors import RefinementError, ValidationGateError
from axquant.planner import plan_quantization, storage_bpw
from axquant.profiles import objective_for, thresholds_for
from axquant.schema import (
    Allocation,
    ArtifactManifest,
    CandidateEntry,
    CompleteCandidateHardware,
    CompleteCandidateMeasurement,
    PlanRequest,
    QualityComparisonReport,
    QuantizationPlan,
    QuantMethod,
    RefinementConfig,
    RefinementMeasurementSet,
    RefinementResult,
    SensitivityReport,
    ValidationReport,
)
from axquant.serde import stable_sha256

log = structlog.get_logger()

COMPLETE_OBJECTIVE_VERSION = "axquant-complete-objective-v2"


@dataclass
class _CandidateState:
    """Internal mutable state for a refinement candidate."""

    candidate_id: str
    plan: QuantizationPlan
    parent_id: str | None
    predicted_loss: float
    measured_loss: float | None = None
    change_description: str = "initial candidate"
    reason: str = "generated by greedy planner"
    budget_impact: float = 0.0
    state: str = "pending"


def _compute_plan_loss(plan: QuantizationPlan) -> float:
    """Compute aggregate predicted loss from a plan's allocations."""
    weights = objective_for(plan.profile).normalized()
    total_loss = 0.0
    total_params = 0
    for allocation in plan.assignments:
        metrics = allocation.metrics.model_dump()
        loss = sum(float(metrics[k]) * w for k, w in weights.items())
        total_loss += loss * allocation.parameters
        total_params += allocation.parameters
    return total_loss / total_params if total_params > 0 else 0.0


def _generate_candidate_id(seed: int, index: int) -> str:
    """Generate a deterministic candidate ID."""
    return f"cand-{seed:04d}-{index:03d}"


def _ax_engine_attention_packing_compatible(plan: QuantizationPlan) -> bool:
    """Require one quantization format for each Qwen attention Q/K/V pack.

    AX Engine packs ``q_proj``, ``k_proj``, and ``v_proj`` together.  MLX-LM
    can convert a mixed-format triplet, but the generated native manifest is
    invalid because the packed tensor layout is no longer representable.
    Reject those refinement variants before conversion rather than discovering
    the incompatibility after writing a full candidate checkpoint.
    """

    groups: dict[str, dict[str, tuple[int, QuantMethod, int | None]]] = {}
    for assignment in plan.assignments:
        marker = ".self_attn."
        if marker not in assignment.module_path:
            continue
        prefix, projection = assignment.module_path.rsplit(marker, 1)
        if projection not in {"q_proj", "k_proj", "v_proj"}:
            continue
        groups.setdefault(prefix, {})[projection] = (
            assignment.bits,
            assignment.method,
            assignment.group_size,
        )
    return all(
        len(set(group.values())) == 1
        for group in groups.values()
        if {"q_proj", "k_proj", "v_proj"}.issubset(group)
    )


def _is_packed_attention_projection(module_path: str) -> bool:
    marker = ".self_attn."
    return marker in module_path and module_path.rsplit(marker, 1)[1] in {
        "q_proj",
        "k_proj",
        "v_proj",
    }


def _is_monotonic_precision_refinement(
    parent: QuantizationPlan,
    child: QuantizationPlan,
) -> bool:
    """Return whether ``child`` only upgrades formats from ``parent``.

    M6 parentage represents an interaction refinement, not merely two plans generated at
    different budgets. A valid child must retain identical tensor coverage, never reduce a
    tensor's precision, and make at least one actual format change.
    """
    parent_assignments = {assignment.tensor: assignment for assignment in parent.assignments}
    child_assignments = {assignment.tensor: assignment for assignment in child.assignments}
    if set(parent_assignments) != set(child_assignments):
        return False
    changed = False
    for tensor, parent_assignment in parent_assignments.items():
        child_assignment = child_assignments[tensor]
        if child_assignment.bits < parent_assignment.bits:
            return False
        if child_assignment.bits == parent_assignment.bits and (
            child_assignment.method != parent_assignment.method
            or child_assignment.group_size != parent_assignment.group_size
        ):
            return False
        if (
            child_assignment.bits,
            child_assignment.method,
            child_assignment.group_size,
        ) != (
            parent_assignment.bits,
            parent_assignment.method,
            parent_assignment.group_size,
        ):
            changed = True
    return changed and child.effective_bpw > parent.effective_bpw


def _canonicalize_ax_engine_attention_packs(
    plan: QuantizationPlan,
    report: SensitivityReport,
) -> QuantizationPlan:
    """Conservatively make each Qwen attention Q/K/V pack runtime-compatible.

    A per-tensor plan may assign different formats inside a packed Q/K/V
    group.  Canonicalize the group to its least-expensive existing format so
    the result remains within the planner budget.  Metrics are restored from
    the measured candidate for each affected tensor; this is not a synthetic
    sensitivity estimate.
    """

    entries = {entry.tensor.name: entry for entry in report.entries}
    groups: dict[str, list[tuple[int, Allocation]]] = {}
    for index, assignment in enumerate(plan.assignments):
        marker = ".self_attn."
        if marker not in assignment.module_path:
            continue
        prefix, projection = assignment.module_path.rsplit(marker, 1)
        if projection in {"q_proj", "k_proj", "v_proj"}:
            groups.setdefault(prefix, []).append((index, assignment))

    weights = objective_for(plan.profile).normalized()
    assignments = list(plan.assignments)
    changed = False
    for members in groups.values():
        projections = {
            assignment.module_path.rsplit(".self_attn.", 1)[1] for _, assignment in members
        }
        signatures = {
            (assignment.bits, assignment.method, assignment.group_size) for _, assignment in members
        }
        if projections != {"q_proj", "k_proj", "v_proj"} or len(signatures) == 1:
            continue
        bits, method, group_size = min(
            signatures,
            key=lambda signature: storage_bpw(signature[0], signature[2]),
        )
        for index, assignment in members:
            entry = entries.get(assignment.tensor)
            if entry is None:
                raise RefinementError(f"missing sensitivity entry for {assignment.tensor}")
            candidate = next(
                (
                    item
                    for item in entry.candidates
                    if item.bits == bits
                    and item.method == method
                    and item.group_size == group_size
                    and item.supported
                ),
                None,
            )
            if candidate is None:
                raise RefinementError(
                    "no measured "
                    f"{bits}-bit candidate for packed attention tensor {assignment.tensor}"
                )
            metric_values = candidate.metrics.model_dump()
            assignments[index] = assignment.model_copy(
                update={
                    "bits": bits,
                    "method": method,
                    "group_size": group_size,
                    "metrics": candidate.metrics,
                    "predicted_loss": sum(
                        float(metric_values[key]) * weight for key, weight in weights.items()
                    ),
                    "reason": "AX Engine packed Q/K/V format canonicalization",
                }
            )
            changed = True

    if not changed:
        return plan
    total_parameters = sum(assignment.parameters for assignment in assignments)
    return plan.model_copy(
        update={
            "assignments": assignments,
            "nominal_bpw": (
                sum(assignment.bits * assignment.parameters for assignment in assignments)
                / total_parameters
            ),
            "effective_bpw": (
                sum(
                    storage_bpw(assignment.bits, assignment.group_size) * assignment.parameters
                    for assignment in assignments
                )
                / total_parameters
            ),
        }
    )


def generate_top_n_plans(
    report: SensitivityReport,
    request: PlanRequest,
    n: int,
    *,
    deadline: float | None = None,
) -> list[QuantizationPlan]:
    """Generate top-N plan variants via beam widening.

    The first plan is the standard greedy allocation.  Subsequent
    variants are produced by perturbing the least-efficient upgrades
    in the greedy solution.  Each variant remains deterministic under
    the plan seed.
    """
    if n < 1:
        raise RefinementError("top_n must be at least 1")

    # Generate the primary plan
    primary_request = request.model_copy(update={"candidate_count": 1})
    primary_plan = _canonicalize_ax_engine_attention_packs(
        plan_quantization(report, primary_request), report
    )
    if not _ax_engine_attention_packing_compatible(primary_plan):
        raise RefinementError("primary plan violates AX Engine attention packing")
    plans = [primary_plan]

    if n == 1:
        return plans

    # Generate an increasing precision ladder. Global replanning can occasionally exchange one
    # high-precision tensor for another even as the total budget grows. Such a plan remains a
    # useful independent candidate, but it is not an M6 parent/child refinement and is therefore
    # excluded from this monotonic interaction chain.
    base_bpw = request.target_bpw
    max_attempts = max(16, n * 4)
    for attempt in range(1, max_attempts + 1):
        if len(plans) >= n:
            break
        if deadline is not None and time.monotonic() >= deadline:
            log.info("refinement_generation_wall_clock_exhausted", plans=len(plans))
            break
        variant_bpw = min(16.0, base_bpw + attempt * 0.1)
        if variant_bpw <= plans[-1].target_bpw:
            break

        variant_request = request.model_copy(
            update={
                "candidate_count": 1,
                "target_bpw": variant_bpw,
                # Preserve the historical upward-variant seed identity. The original
                # alternating search assigned positive offsets to even attempt numbers.
                "random_seed": request.random_seed + attempt * 2,
            }
        )
        try:
            variant_plan = _canonicalize_ax_engine_attention_packs(
                plan_quantization(report, variant_request), report
            )
            if not _ax_engine_attention_packing_compatible(variant_plan):
                log.debug("variant_plan_incompatible", index=attempt, target_bpw=variant_bpw)
                continue
            if not _is_monotonic_precision_refinement(plans[-1], variant_plan):
                log.debug(
                    "variant_plan_non_monotonic",
                    index=attempt,
                    target_bpw=variant_bpw,
                )
                continue
            plans.append(variant_plan)
        except Exception:
            # If a variant is infeasible, skip it
            log.debug("variant_plan_infeasible", index=attempt, target_bpw=variant_bpw)
            continue

    return plans


def coordinate_descent_swap(
    plan: QuantizationPlan,
    report: SensitivityReport,
    request: PlanRequest,
    *,
    swap_radius: int = 5,
) -> QuantizationPlan | None:
    """Attempt bounded coordinate descent swaps on a plan.

    For each of the top-`swap_radius` tensors with highest predicted loss,
    try upgrading to the next precision level if budget allows.  Returns
    an improved plan or None if no improvement is found.
    """
    weights = objective_for(plan.profile).normalized()

    # Sort allocations by predicted loss (highest first)
    sorted_allocations = sorted(plan.assignments, key=lambda a: a.predicted_loss, reverse=True)
    candidates_to_try = sorted_allocations[:swap_radius]

    improved = False
    new_assignments = list(plan.assignments)

    for alloc in candidates_to_try:
        if alloc.bits >= 16 or _is_packed_attention_projection(alloc.module_path):
            continue

        # Find the sensitivity entry for this tensor
        entry = None
        for e in report.entries:
            if e.tensor.name == alloc.tensor:
                entry = e
                break
        if entry is None:
            continue

        # Try the closest precision upgrade that satisfies the hardware policy
        upgrade = None
        for candidate in sorted(entry.candidates, key=lambda c: c.bits):
            if (
                candidate.bits > alloc.bits
                and candidate.supported
                and candidate.bits in request.hardware.supported_bits
                and candidate.method in request.hardware.supported_methods
                and (
                    candidate.bits == 16
                    or candidate.group_size in request.hardware.supported_group_sizes
                )
            ):
                upgrade = candidate
                break

        if upgrade is None:
            continue

        # Check budget impact
        current_storage = storage_bpw(alloc.bits, alloc.group_size) * alloc.parameters
        new_storage = storage_bpw(upgrade.bits, upgrade.group_size) * alloc.parameters
        budget_delta = (new_storage - current_storage) / sum(a.parameters for a in plan.assignments)

        if plan.effective_bpw + budget_delta > request.target_bpw:
            continue

        # Apply the upgrade together with the candidate's metrics so that
        # downstream loss tracking reflects the new precision
        metric_values = upgrade.metrics.model_dump()
        upgraded_loss = sum(float(metric_values[k]) * w for k, w in weights.items())
        for i, a in enumerate(new_assignments):
            if a.tensor == alloc.tensor:
                new_assignments[i] = a.model_copy(
                    update={
                        "bits": upgrade.bits,
                        "method": upgrade.method,
                        "group_size": upgrade.group_size,
                        "metrics": upgrade.metrics,
                        "predicted_loss": upgraded_loss,
                        "reason": f"coordinate descent upgrade from {alloc.bits} to {upgrade.bits}",
                    }
                )
                improved = True
                break

        if improved:
            break  # One swap per iteration

    if not improved:
        return None

    # Reconstruct plan with updated assignments
    total_params = sum(a.parameters for a in new_assignments)
    nominal_bpw = sum(a.bits * a.parameters for a in new_assignments) / total_params
    effective_bpw = (
        sum(storage_bpw(a.bits, a.group_size) * a.parameters for a in new_assignments)
        / total_params
    )

    refined = plan.model_copy(
        update={
            "assignments": new_assignments,
            "nominal_bpw": nominal_bpw,
            "effective_bpw": effective_bpw,
        }
    )
    return refined if _ax_engine_attention_packing_compatible(refined) else None


def refine_candidates(
    report: SensitivityReport,
    request: PlanRequest,
    config: RefinementConfig,
) -> RefinementResult:
    """Run the global candidate refinement loop.

    1. Generate top-N initial plans
    2. Evaluate candidates (proxy-based in framework)
    3. Apply coordinate descent swaps
    4. Track immutable history
    5. Stop on convergence / budget exhaustion
    """
    start_time = time.monotonic()
    history: list[CandidateEntry] = []
    evaluations_used = 0

    # Step 1: Generate top-N initial plans
    plans = generate_top_n_plans(
        report,
        request,
        config.top_n,
        deadline=start_time + config.wall_clock_seconds,
    )
    if not plans:
        raise RefinementError("no feasible plans could be generated")

    # Track candidate states
    candidates: list[_CandidateState] = []
    for i, plan in enumerate(plans):
        cand_id = _generate_candidate_id(config.random_seed, i)
        parent_id = None if i == 0 else _generate_candidate_id(config.random_seed, i - 1)
        loss = _compute_plan_loss(plan)
        state = _CandidateState(
            candidate_id=cand_id,
            plan=plan,
            parent_id=parent_id,
            predicted_loss=loss,
            change_description=(
                "initial greedy plan"
                if i == 0
                else f"budget-perturbed precision allocation variant {i}"
            ),
            reason=(
                "top-N generation"
                if i == 0
                else f"monotonic top-N precision refinement of {parent_id}"
            ),
            budget_impact=plan.effective_bpw - request.target_bpw,
        )
        candidates.append(state)
        history.append(
            CandidateEntry(
                candidate_id=cand_id,
                parent_id=parent_id,
                plan_sha256=stable_sha256(plan),
                change_description=state.change_description,
                reason=state.reason,
                predicted_bpw=plan.effective_bpw,
                predicted_loss=loss,
                budget_impact=state.budget_impact,
                state="pending",
            )
        )
        evaluations_used += 1

    # Step 2-5: Iterative refinement
    converged = False
    iterations_used = 0

    for iteration in range(config.max_iterations):
        iterations_used = iteration + 1

        # Check wall-clock budget
        elapsed = time.monotonic() - start_time
        if elapsed > config.wall_clock_seconds:
            log.info("refinement_wall_clock_exhausted", elapsed=elapsed)
            break

        # Check evaluation budget
        if evaluations_used >= config.evaluation_budget:
            log.info("refinement_eval_budget_exhausted", evaluations=evaluations_used)
            break

        # Select the current best candidate
        best_candidate = min(candidates, key=lambda c: c.predicted_loss)

        # Try coordinate descent within the candidate's own search budget.  Top-N
        # variants intentionally widen or tighten the original request, and
        # reusing the primary budget makes every widened variant impossible to
        # refine further.
        candidate_request = request.model_copy(
            update={
                "target_bpw": best_candidate.plan.target_bpw,
                "random_seed": best_candidate.plan.random_seed,
            }
        )
        improved_plan = coordinate_descent_swap(
            best_candidate.plan,
            report,
            candidate_request,
            swap_radius=config.swap_radius,
        )

        if improved_plan is None:
            # No improvement found - check convergence
            converged = True
            break

        new_loss = _compute_plan_loss(improved_plan)
        improvement = best_candidate.predicted_loss - new_loss

        # Check convergence threshold
        if improvement < config.convergence_threshold:
            converged = True
            break

        # Record the improved candidate
        new_id = _generate_candidate_id(config.random_seed, len(candidates) + iterations_used)
        new_state = _CandidateState(
            candidate_id=new_id,
            plan=improved_plan,
            parent_id=best_candidate.candidate_id,
            predicted_loss=new_loss,
            change_description=(
                f"coordinate descent swap: {best_candidate.predicted_loss:.6f} -> {new_loss:.6f}"
            ),
            reason=f"improvement of {improvement:.6f} via precision upgrade",
            budget_impact=improved_plan.effective_bpw - request.target_bpw,
            state="selected",
        )
        candidates.append(new_state)
        evaluations_used += 1

        history.append(
            CandidateEntry(
                candidate_id=new_id,
                parent_id=best_candidate.candidate_id,
                plan_sha256=stable_sha256(improved_plan),
                change_description=new_state.change_description,
                reason=new_state.reason,
                predicted_bpw=improved_plan.effective_bpw,
                predicted_loss=new_loss,
                budget_impact=new_state.budget_impact,
                state="selected",
            )
        )

        log.debug(
            "refinement_iteration",
            iteration=iterations_used,
            loss=new_loss,
            improvement=improvement,
        )

    # Select the final best candidate
    final_best = min(candidates, key=lambda c: c.predicted_loss)
    selected_sha = stable_sha256(final_best.plan)

    # Mark rejected candidates in history
    for entry in history:
        if entry.candidate_id != final_best.candidate_id and entry.state == "pending":
            entry.state = "rejected"

    proxy_warning = (
        "Proxy-only refinement is development evidence and cannot satisfy release "
        "selection without holdout-bound complete-candidate measurements (QP1)."
    )
    warnings = [proxy_warning]
    if config.holdout_measurement_set_sha256:
        warnings.append(
            "holdout_measurement_set_sha256 is configured; call select_complete_candidate "
            "with a matching RefinementMeasurementSet to bind holdout evidence."
        )
    return RefinementResult(
        config=config,
        history=history,
        candidate_plans={candidate.candidate_id: candidate.plan for candidate in candidates},
        selected_candidate_id=final_best.candidate_id,
        selected_plan=final_best.plan,
        selected_plan_sha256=selected_sha,
        selection_basis="proxy",
        evidence_label="proxy-development",
        holdout_measurement_set_sha256=config.holdout_measurement_set_sha256,
        warnings=warnings,
        iterations_used=iterations_used,
        evaluations_used=evaluations_used,
        converged=converged,
    )


def select_complete_candidate(
    refinement: RefinementResult,
    measurements: RefinementMeasurementSet,
) -> RefinementResult:
    """Select a candidate only from checksum-bound complete-model evidence."""
    measurement_digest = stable_sha256(measurements)
    expected_holdout = (
        refinement.config.holdout_measurement_set_sha256
        or refinement.holdout_measurement_set_sha256
    )
    if expected_holdout is not None and measurement_digest != expected_holdout:
        raise RefinementError(
            "holdout measurement set digest does not match refinement binding: "
            f"expected {expected_holdout}, got {measurement_digest}"
        )
    candidates_by_id = refinement.candidate_plans
    history_by_id = {entry.candidate_id: entry for entry in refinement.history}
    measurements_by_candidate: dict[str, list[CompleteCandidateMeasurement]] = {}
    for measurement_record in measurements.measurements:
        history = history_by_id.get(measurement_record.candidate_id)
        if measurement_record.candidate_id not in candidates_by_id or history is None:
            raise RefinementError(
                f"measurement references unknown candidate {measurement_record.candidate_id}"
            )
        if history.plan_sha256 != measurement_record.plan_sha256:
            raise RefinementError(
                f"measurement plan digest differs for {measurement_record.candidate_id}"
            )
        if candidates_by_id[measurement_record.candidate_id].profile != measurement_record.profile:
            raise RefinementError(
                f"measurement profile differs for {measurement_record.candidate_id}"
            )
        measurements_by_candidate.setdefault(measurement_record.candidate_id, []).append(
            measurement_record
        )
    valid = {
        candidate_id: records
        for candidate_id, records in measurements_by_candidate.items()
        if all(record.validation_passed for record in records)
    }
    if not valid:
        raise RefinementError("no complete-model candidate passed validation")
    selected_candidate_id, _selected_measurements = min(
        valid.items(),
        key=lambda item: (
            max(record.objective_loss for record in item[1]),
            max(record.measured_bpw for record in item[1]),
            item[0],
        ),
    )
    updated_history = []
    for entry in refinement.history:
        complete_measurements = measurements_by_candidate.get(entry.candidate_id, [])
        updated_history.append(
            entry.model_copy(
                update={
                    "measured_bpw": (
                        max(record.measured_bpw for record in complete_measurements)
                        if complete_measurements
                        else None
                    ),
                    "measured_loss": (
                        max(record.objective_loss for record in complete_measurements)
                        if complete_measurements
                        else None
                    ),
                    "state": (
                        "selected" if entry.candidate_id == selected_candidate_id else "rejected"
                    ),
                }
            )
        )
    selected_plan = candidates_by_id[selected_candidate_id]
    warnings = [
        warning for warning in refinement.warnings if "Proxy-only refinement" not in warning
    ]
    warnings.append(
        f"Selection bound to holdout complete-candidate measurements (digest {measurement_digest})."
    )
    return refinement.model_copy(
        update={
            "history": updated_history,
            "selected_candidate_id": selected_candidate_id,
            "selected_plan": selected_plan,
            "selected_plan_sha256": stable_sha256(selected_plan),
            "selection_basis": "complete-model",
            "evidence_label": "holdout-bound",
            "holdout_measurement_set_sha256": measurement_digest,
            "warnings": warnings,
        }
    )


def build_complete_candidate_measurement(
    *,
    candidate_id: str,
    measurement_id: str | None = None,
    plan: QuantizationPlan,
    artifact: ArtifactManifest,
    artifact_sha256: str,
    quality: QualityComparisonReport,
    quality_sha256: str,
    validation: ValidationReport,
    validation_sha256: str,
) -> CompleteCandidateMeasurement:
    """Build checksum-bound complete-model evidence from release artifacts."""
    plan_sha256 = stable_sha256(plan)
    if artifact.plan_sha256 != plan_sha256:
        raise RefinementError("artifact manifest does not match the refinement candidate plan")
    if artifact.profile != plan.profile or validation.profile != plan.profile:
        raise RefinementError("artifact, validation, and candidate plan profiles differ")
    if quality.candidate_model != validation.candidate_model:
        raise RefinementError("quality and validation candidate identities differ")
    if quality.reference_model != validation.reference_model:
        raise RefinementError("quality and validation reference identities differ")
    if validation.thresholds != thresholds_for(plan.profile):
        raise RefinementError("validation does not use the authoritative profile thresholds")
    expected_validation_passed = not any(issue.severity == "error" for issue in validation.issues)
    if validation.passed != expected_validation_passed:
        raise RefinementError("validation pass status is inconsistent with its issues")
    if validation.comparisons.get("artifact.candidate_source_sha256") != artifact_sha256:
        raise RefinementError("validation size evidence does not bind the artifact manifest")
    if (
        validation.comparisons.get("artifact.candidate_weight_bytes")
        != artifact.weight_file_size_bytes
    ):
        raise RefinementError("validation size evidence does not match artifact weight bytes")

    quality_retention = quality.aggregate.retention
    if quality_retention is None:
        raise RefinementError("quality comparison has no aggregate retention")
    perplexity_ratio = quality.perplexity_ratio
    if perplexity_ratio is None or perplexity_ratio <= 0.0:
        raise RefinementError("quality comparison has no positive perplexity ratio")

    def required_metric(name: str) -> float:
        value = validation.comparisons.get(name)
        if not isinstance(value, (int, float)) or isinstance(value, bool):
            raise RefinementError(f"validation is missing numeric {name}")
        return float(value)

    def required_text(name: str) -> str:
        value = validation.comparisons.get(name)
        if not isinstance(value, str) or not value:
            raise RefinementError(f"validation is missing {name}")
        return value

    unified_memory = validation.comparisons.get("hardware.unified_memory_bytes")
    if not isinstance(unified_memory, int) or isinstance(unified_memory, bool):
        raise RefinementError("validation is missing hardware.unified_memory_bytes")

    mtp_retention = required_metric("mtp.acceptance_retention")
    mtp_speedup = required_metric("hardware.effective_speedup")
    peak_memory_ratio = required_metric("hardware.peak_memory_ratio")
    kernel_fallbacks = validation.comparisons.get("hardware.kernel_fallbacks")
    if not isinstance(kernel_fallbacks, int) or isinstance(kernel_fallbacks, bool):
        raise RefinementError("validation is missing hardware.kernel_fallbacks")
    if peak_memory_ratio <= 0.0:
        raise RefinementError("hardware.peak_memory_ratio must be positive")

    if validation.passed:
        thresholds = validation.thresholds
        failed_release_metrics: list[str] = []
        if quality_retention < thresholds.minimum_aggregate_quality_retention:
            failed_release_metrics.append("quality.aggregate_retention")
        if perplexity_ratio > 1.0 + thresholds.max_perplexity_relative_increase:
            failed_release_metrics.append("quality.perplexity_ratio")
        if mtp_retention < thresholds.minimum_mtp_acceptance_retention:
            failed_release_metrics.append("mtp.acceptance_retention")
        if mtp_speedup < thresholds.min_effective_speedup:
            failed_release_metrics.append("hardware.effective_speedup")
        if peak_memory_ratio > thresholds.max_peak_memory_ratio:
            failed_release_metrics.append("hardware.peak_memory_ratio")
        if kernel_fallbacks != 0:
            failed_release_metrics.append("hardware.kernel_fallbacks")
        if failed_release_metrics:
            raise RefinementError(
                "passing validation contains failed complete-model metrics: "
                f"{failed_release_metrics}"
            )

        if thresholds.require_artifact_size:
            size_ratio = required_metric("artifact.weight_size_ratio")
            if size_ratio > thresholds.max_weight_size_ratio:
                from axquant.release_exceptions import release_exception_allows_size

                try:
                    release_exception_allows_size(validation, plan=plan)
                except (ValidationGateError, ValueError) as exc:
                    raise RefinementError(
                        f"passing validation has an ungoverned size overage: {exc}"
                    ) from exc
            elif validation.release_exceptions:
                raise RefinementError(
                    "passing validation contains an unnecessary release exception"
                )
        elif validation.release_exceptions:
            raise RefinementError(
                "validation without an artifact-size gate contains a release exception"
            )

    weights = objective_for(plan.profile).normalized()
    quality_weight = (
        weights["output_kl"]
        + weights["hidden_state_error"]
        + weights["cosine_distance"]
        + weights["token_disagreement"]
        + weights["task_loss_delta"]
        + weights["long_context_loss"]
    )
    latency_weight = weights["prefill_latency_cost"] + weights["decode_latency_cost"]
    quality_loss = 0.5 * max(0.0, 1.0 - quality_retention) + 0.5 * perplexity_ratio
    objective_loss = (
        quality_weight * quality_loss
        + weights["mtp_acceptance_loss"] * max(0.0, 1.0 - mtp_retention)
        + weights["peak_memory_cost"] * peak_memory_ratio
        + latency_weight / max(mtp_speedup, 1e-12)
    )
    return CompleteCandidateMeasurement(
        candidate_id=candidate_id,
        measurement_id=measurement_id or candidate_id,
        candidate_model=validation.candidate_model,
        profile=plan.profile,
        plan_sha256=plan_sha256,
        artifact_manifest_sha256=artifact_sha256,
        quality_comparison_sha256=quality_sha256,
        validation_sha256=validation_sha256,
        measured_bpw=artifact.measured_total_bpw,
        objective_loss=objective_loss,
        quality_retention=quality_retention,
        perplexity_ratio=perplexity_ratio,
        mtp_acceptance_retention=mtp_retention,
        mtp_speedup=mtp_speedup,
        peak_memory_ratio=peak_memory_ratio,
        hardware=CompleteCandidateHardware(
            device_name=required_text("hardware.device_name"),
            chip=required_text("hardware.chip"),
            unified_memory_bytes=unified_memory,
            os_version=required_text("hardware.os_version"),
            ax_engine_version=required_text("software.ax_engine"),
            mlx_version=required_text("software.mlx"),
            mlx_lm_version=required_text("software.mlx_lm"),
            power_mode=required_text("hardware.power_mode"),
            kernel_fallbacks=kernel_fallbacks,
        ),
        validation_passed=validation.passed,
    )
